[package]
name = "string_engine"
version = "0.1.0"
authors = ["Thibaud Colas <thibaudcolas@gmail.com>"]
edition = "2018"

[lib]
name = "string_engine"
crate-type = ["dylib"]

[dependencies]
htmlescape = "0.3.1"

[dependencies.pyo3]
version = "0.9.2"
features = ["extension-module"]
